function showCustomer(data) {
    var element = document.getElementById("showCustomerTBody");
    element.innerHTML = "";
    var rowElement = document.createElement("tr");
    var firstColumn = document.createElement("td");
    var secondColumn = document.createElement("td");
    var thirdColumn = document.createElement("td");
    var fourthColumn = document.createElement("td");
    var fifthColumn = document.createElement("td");
    var sixthColumn = document.createElement("td");
    var seventhColumn = document.createElement("td");
    var eighthColumn = document.createElement("td");
    var ninethColumn = document.createElement("td");
    var tenthColumn = document.createElement("td");
    var eleventhColumn = document.createElement("td");
    var firstColumnText = document.createTextNode(data.Id);
    var secondColumnText = document.createTextNode(data.Name);
    var thirdColumnText = document.createTextNode(data.Address);
    var fourthColumnText = document.createTextNode(data.Address2);
    var fifthColumnText = document.createTextNode(data.Zip);
    var sixthColumnText = document.createTextNode(data.City);
    var seventhColumnText = document.createTextNode(data.Country);
    var eighthColumnText = document.createTextNode(data.Email);
    var ninethColumnText = document.createTextNode(data.Phone);
    var tenthColumnText = document.createTextNode(data.ClientId);
    var eleventhColumnText = document.createTextNode(data.Projects);
    rowElement.appendChild(firstColumn);
    rowElement.appendChild(secondColumn);
    rowElement.appendChild(thirdColumn);
    rowElement.appendChild(fourthColumn);
    rowElement.appendChild(fifthColumn);
    rowElement.appendChild(sixthColumn);
    rowElement.appendChild(seventhColumn);
    rowElement.appendChild(eighthColumn);
    rowElement.appendChild(ninethColumn);
    rowElement.appendChild(tenthColumn);
    rowElement.appendChild(eleventhColumn);
    firstColumn.appendChild(firstColumnText);
    secondColumn.appendChild(secondColumnText);
    thirdColumn.appendChild(thirdColumnText);
    fourthColumn.appendChild(fourthColumnText);
    fifthColumn.appendChild(fifthColumnText);
    sixthColumn.appendChild(sixthColumnText);
    seventhColumn.appendChild(seventhColumnText);
    eighthColumn.appendChild(eighthColumnText);
    ninethColumn.appendChild(ninethColumnText);
    tenthColumn.appendChild(tenthColumnText);
    eleventhColumn.appendChild(eleventhColumnText);
    element.appendChild(rowElement);
}